
export const productsData = [
    {
        imagePath: '/Users/adnanrizvi/.gemini/antigravity/brain/aeb6f45d-7c61-4560-83e4-8ca997ccb292/uploaded_image_0_1766729398127.jpg',
        name: 'Pink Self-Care Gift Basket',
        description: 'Indulge in luxury with our Pink Self-Care Gift Basket, a curated collection of premium beauty essentials and accessories. This elegant basket features a beautiful marble-effect mug, cosmetics, jewelry accessories, decorative items, and more. Perfect for birthdays, anniversaries, or just to show someone you care. Each item is carefully selected to create a memorable gifting experience.',
        shortDescription: 'Luxurious self-care gift basket with beauty essentials and accessories in elegant pink tones',
        price: 2499,
        stock: 25,
        category: 'Gifts',
        badge: 'Trending',
        discount: 10,
        isFeatured: true,
    },
    {
        imagePath: '/Users/adnanrizvi/.gemini/antigravity/brain/aeb6f45d-7c61-4560-83e4-8ca997ccb292/uploaded_image_1_1766729398127.png',
        name: '50th Anniversary LED Light',
        description: 'Celebrate 50 amazing years of love with this stunning heart-shaped LED light. Featuring elegant engraving with "50 AMAZING YEARS" and romantic details including weeks, months, days, and hours together. The warm LED glow creates a beautiful ambiance, making it a perfect keepsake for golden anniversary celebrations. Comes with a wooden base for elegant display.',
        shortDescription: 'Beautiful heart-shaped LED light celebrating 50 years of love, perfect anniversary gift',
        price: 1299,
        stock: 30,
        category: 'Personalized',
        badge: 'Popular',
        discount: 5,
        isFeatured: false,
    },
    {
        imagePath: '/Users/adnanrizvi/.gemini/antigravity/brain/aeb6f45d-7c61-4560-83e4-8ca997ccb292/uploaded_image_2_1766729398127.jpg',
        name: 'Personalized Red Leather Gift Set',
        description: 'Elevate your gifting with this premium 4-piece personalized leather gift set in rich burgundy. The set includes a long wallet, passport holder, cardholder, and keychain, all beautifully presented in an elegant black gift box. Each piece can be customized with a name, making it a thoughtful and sophisticated gift for professionals, travelers, or anyone who appreciates fine accessories.',
        shortDescription: 'Elegant 4-piece personalized leather gift set in rich burgundy with wallet and accessories',
        price: 3499,
        stock: 15,
        category: 'Personalized',
        badge: 'Premium',
        discount: 15,
        isFeatured: true,
    },
    {
        imagePath: '/Users/adnanrizvi/.gemini/antigravity/brain/aeb6f45d-7c61-4560-83e4-8ca997ccb292/uploaded_image_3_1766729398127.jpg',
        name: 'Happy Birthday Gift Box',
        description: 'Make birthdays extra special with this delightful gift box featuring LED fairy lights spelling "HAPPY BIRTHDAY", beauty products, accessories, and decorative flowers. The box includes nail polish, beauty tools, jewelry pieces, and charming pink decorative elements. Perfect for surprising friends, family, or loved ones on their special day.',
        shortDescription: 'Delightful birthday gift box with LED lights, beauty products, and decorative elements',
        price: 1899,
        stock: 35,
        category: 'Gifts',
        badge: 'New Arrival',
        discount: 0,
        isFeatured: false,
    },
    {
        imagePath: '/Users/adnanrizvi/.gemini/antigravity/brain/aeb6f45d-7c61-4560-83e4-8ca997ccb292/uploaded_image_4_1766729398127.jpg',
        name: 'Personalized Tumblers Set',
        description: 'Stay hydrated in style with this set of 4 personalized insulated tumblers. Available in beautiful colors - soft pink, vibrant red, hot pink, and matte black - each tumbler can be customized with a name in elegant script. The 40oz capacity with straw makes them perfect for daily use, gym sessions, or outdoor activities. Premium insulation keeps drinks cold for 24 hours or hot for 12 hours.',
        shortDescription: 'Set of 4 personalized insulated tumblers with custom names in vibrant colors',
        price: 2199,
        stock: 40,
        category: 'Personalized',
        badge: 'Trending',
        discount: 12,
        isFeatured: true,
    },

    {
        imagePath: '/Users/adnanrizvi/.gemini/antigravity/brain/aeb6f45d-7c61-4560-83e4-8ca997ccb292/uploaded_image_1766731037672.png',
        name: 'Personalized Name Ring with Heart',
        description: 'Express your love with this elegant personalized name ring featuring a delicate heart accent. Crafted in beautiful gold tone, this adjustable ring can be customized with any name in stylish script font. The unique design combines the name with a charming heart symbol, making it a perfect gift for loved ones, anniversaries, or special occasions. The adjustable band ensures a comfortable fit for any finger size. Perfect for gifting to someone special or treating yourself to a meaningful piece of jewelry.',
        shortDescription: 'Elegant gold-toned personalized name ring with heart accent, adjustable fit',
        price: 899,
        stock: 50,
        category: 'Personalized',
        badge: 'Trending',
        discount: 10,
        isFeatured: true,
    },

    {
        imagePath: '/Users/adnanrizvi/.gemini/antigravity/brain/aeb6f45d-7c61-4560-83e4-8ca997ccb292/uploaded_image_0_1766731744938.png',
        name: 'Magnetic Levitating Moon Lamp',
        description: 'Experience the magic of the cosmos with our stunning Magnetic Levitating Moon Lamp. This 3D printed moon replica floats effortlessly above its wooden base using advanced magnetic levitation technology. The warm LED glow creates a mesmerizing ambiance perfect for bedrooms, living rooms, or offices. The realistic lunar surface details make it an extraordinary conversation piece and a unique gift for space enthusiasts, tech lovers, or anyone who appreciates innovative home decor. USB powered with touch control for easy operation.',
        shortDescription: '3D printed levitating moon lamp with magnetic base and warm LED lighting',
        price: 2999,
        stock: 20,
        category: 'Home Decor',
        badge: 'Premium',
        discount: 15,
        isFeatured: true,
    },
    {
        imagePath: '/Users/adnanrizvi/.gemini/antigravity/brain/aeb6f45d-7c61-4560-83e4-8ca997ccb292/uploaded_image_1_1766731744938.png',
        name: 'Custom Sound Wave Acrylic Display',
        description: 'Preserve your most precious moments forever with our Custom Sound Wave Acrylic Display. Transform meaningful audio - wedding vows, "I love you", a baby\'s first words, or favorite song - into stunning visual art. Each piece is laser-engraved on premium acrylic with your custom sound wave pattern and personalized date or message. The elegant design makes it a perfect anniversary gift, wedding keepsake, or romantic gesture that captures the sound of love in a beautiful, tangible form. Comes with wooden stand for display.',
        shortDescription: 'Personalized acrylic sound wave art with custom audio visualization and date',
        price: 1799,
        stock: 30,
        category: 'Personalized',
        badge: 'Best Seller',
        discount: 10,
        isFeatured: true,
    },
    {
        imagePath: '/Users/adnanrizvi/.gemini/antigravity/brain/aeb6f45d-7c61-4560-83e4-8ca997ccb292/uploaded_image_2_1766731744938.png',
        name: 'Smart Coffee Mug Warmer',
        description: 'Never drink cold coffee again with our Smart Coffee Mug Warmer. This sleek, minimalist warming pad keeps your beverages at the perfect temperature throughout your workday. USB-powered for convenience, it features auto shut-off safety and works with any mug or cup. Ideal for busy professionals, students, or anyone who enjoys hot beverages at their own pace. The modern black design complements any desk setup, making it a practical yet thoughtful gift for coffee and tea lovers. Maintains temperature at 55°C (131°F).',
        shortDescription: 'USB-powered smart mug warmer keeps beverages hot, perfect for desk use',
        price: 699,
        stock: 60,
        category: 'Accessories',
        badge: 'Popular',
        discount: 5,
        isFeatured: false,
    },
    {
        imagePath: '/Users/adnanrizvi/.gemini/antigravity/brain/aeb6f45d-7c61-4560-83e4-8ca997ccb292/uploaded_image_3_1766731744938.png',
        name: 'Gratitude Self-Care Essentials Box',
        description: 'Embrace mindfulness and self-love with our Gratitude Self-Care Essentials Box. This thoughtfully curated set includes a premium Gratitude journal for daily reflections, a luxurious silk sleep mask for restful nights, a satin scrunchie to protect your hair, calming aromatherapy oil, and dried lavender sprigs. Beautifully packaged in an elegant white box, it\'s the perfect gift for birthdays, self-care Sundays, or showing someone you care about their wellbeing. Encourage relaxation, gratitude, and peaceful moments with this complete wellness package.',
        shortDescription: 'Curated self-care gift box with gratitude journal, silk sleep mask, and aromatherapy',
        price: 1499,
        stock: 35,
        category: 'Gifts for Her',
        badge: 'Trending',
        discount: 12,
        isFeatured: true,
    },
];
